### ISSUE TITLE
Any chance this can be supported on other models such as NCS314?

### ISSUE THREAD

**Issue by bravecorvus** [SebiTimeWaster/Slave-Nixie-Clock#1]
Any way this could be supported on other GRA and AFCH models such as NCS314?

**Comment by SebiTimeWaster** [comment]
yeah, why not, the problem is that all models seem to have some special quirks / different electronic layout, so it needs to be adapted to the specific model... if you sponsor me the specific model i will adapt it immediately.

**Comment by bravecorvus** [comment]
What do you mean by sponsor? my specific model is the IN-14 NCS 314 Shield model [ebay link](https://www.ebay.com/itm/Nixie-Tubes-Clock-IN-14-Arduino-Shield-NCS314-Remote-GPS-Temp-WITH-TUBES/162198121548?hash=item25c3c2ec4c:g:vy4AAOSwvGZZxSdO)

**Comment by bravecorvus** [comment]
currently using and old version of [this firmware](https://github.com/afch/NixeTubesShieldNCS314) on the arduino board

**Comment by SebiTimeWaster** [comment]
well, sponsoring means you buy me one so i can develop on it... without the clock it is really hard to impossible to adapt the code.

**Comment by bravecorvus** [comment]
ahh I see. Well I'm running a a college student's budget right now so I don't think I will be able to. But thanks anyways.

**Comment by bravecorvus** [comment]
i'll just ask Afch directly
