### ISSUE TITLE
Hardware Modifications

### ISSUE THREAD

**Issue by burdettadam** [SebiTimeWaster/Slave-Nixie-Clock#2]
I notice from the picture in the readme that your power cable is connected at a different location.  I am interested in knowing what hardware changes you have made and what your serial connection looks like.
I hope to use your repo to make my nixie-clock a IoT device by controlling it with a raspberry pi.

Would you be willing to post a few pictures of your set up with a short description?

**Comment by SebiTimeWaster** [comment]
hi, i actually made no modification at all. the lower pcb has solder pads for power and usb, i just soldered two cables to it.

for your project, it should work out of the box. the raspi can run python easily, so it could be really a matter of just connecting the clock and running the example python script you'll find in this repo. 

have fun!
